### ISSUE TITLE
client with {{ mongodb44recommended }} is not able to connect with up-to-date-cluster

### ISSUE THREAD

**Issue by rdxmb** [percona/k8spsmdb-docs#72]
Trying to do this: https://docs.percona.com/percona-operator-for-mongodb/users.html#unprivileged-users

However, the connection from ` percona/percona-server-mongodb:{{ mongodb44recommended }}`-client to a cluster running `crVersion: 1.14.0` with `image: percona/percona-server-mongodb:6.0.4-3` cannot be established. As there are confusing errors with TLS this took me hours...

This should be changed to an actual mongodb-version and mongosh

**Comment by fiowro** [comment]
The issue was fixed
